<a href="https://colab.research.google.com/github/reban87/ML-Projects/blob/main/00_tensorflow_fundamentals_Reban_Aryal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow.

we are going to cover:
* Introduction to tensor
*Getting information from tensors
*Manipulating tensors
*Tensor and Numpy
* using @tf.function (a way to speed your regular python functions)
*using GPUs with Tensorflow 
*Exercise to try for yourself


## Introduction to Tensor


In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


## Creating tensors with tf.constants ()

In [ ]:
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension of a tens (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector 
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the diimension of vector
vector.ndim

1

In [ ]:
# create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#check the dimension of matrix
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix =tf.constant([[10.,7.],
                             [3.,2.],
                            [8.,9.]],dtype=tf.float16)# speicify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#the number of dimension of another matrix
another_matrix.ndim

2

In [ ]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6],
                     [7,8,9],
                     [10,11,12],
                     [13,14,15]]])
tensor

<tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [ ]:
#the number of dimension of tensor
tensor.ndim

3

# what we have created so far

* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
*Matrix: 2-dimensional array of numbers
*Tensor: an n- dimensional array of numbers (where n can be any number, a 0- dimensional tensor is scalar, a 1-dimensional tensor is vector)

### Creating Tensors with tf.variables

In [ ]:
#create the same tensor with tf.variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#lets try to change unchangeable tensor
#unchangeable_tensor[0]=7 # doesnt take assignment operation hence we got error...
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

#### what we got from the above error is that, we can not update the constant tensors. Only Variable tensor can be updated.

### creating random tensors 
Random tensors are tensors of some arbitary size which contain random numbers

In [ ]:
# create two random ( but the same) tensor
random_1 = tf.random.Generator.from_seed(42) #sets seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

In [ ]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

In [ ]:
#are random_1 and random_2 equal?

random_1, random_2, random_1==random_2

### Shuffle the order of elements in a Tensor

In [ ]:
# Shuffle a Tensor (Valuable when you want to shuffle your data so that the inherent order doesnt affect learning) Eg.while traning 10000 pizza
 image and 500 pasta image, if we shuffle then it would be good while training.
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim

In [ ]:
#shuffle our non shuffle tensor
tf.random.shuffle(not_shuffled)

NameError: ignored

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:











# create some more shuffled tensors
shuffle=tf.constant([[1,2,3],
                     [3,4,5],
                     [5,6,7],
                     [7,8,9]])
shuffle

In [ ]:
shuffle.ndim

NameError: ignored

In [ ]:
tf.random.shuffle(shuffle)

NameError: ignored

In [ ]:
#what if i set the value of seed
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(shuffle,seed=42) #operation level random seed

In [ ]:
# Note: what we just realize is, if we want our shuffled tensors to be in the same order, we have got to use the global level random seed 
as well as the operation level random seed:

### Otherways to make Tensor

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into Tensor
The main differnce between Numpy arrays and Tensorflow tesnsors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also turn Numpy arrays into Tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A
#X=tf.constant(some_matrix) #capital  for matrix of tensor
#y= tf.constant(vector) #non capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors (tensor attributes)
When dealing with the tensor, you probably want to be aware of the following attributes
* Shape
* size
* Axis or dimension
* Rank

In [ ]:
#create a rank 4 tensor( 4 dimension)
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
# get various attributes of our tensors
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimension(rank)",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Element along the zero axis:",rank_4_tensor.shape[0])
print("Element along the last axis",rank_4_tensor.shape[-1])
print("total number of elements in our tensor",tf.size(rank_4_tensor))
print("total number of elements in our tensor",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimension(rank) 4
Shape of tensor: (2, 3, 4, 5)
Element along the zero axis: 2
Element along the last axis 5
total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor 120


 ### Indexing Tensors
 Tensors can be indexed just like Python lists.

In [ ]:
#Get the first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor (2 dimensions)
rank_2_tensor= tf.constant([[1,2],
                            [2,3]])
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [ ]:
some_list=[1,2,3,4]
some_list,some_list[-1]


([1, 2, 3, 4], 4)

In [ ]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis] # ... means hami sanga vayeko dimension : tensor ko 
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[2],
        [3]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[2],
        [3]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

### Manipulating the tensors (tensor operations)
* Basic Operations'+.,'-','/','*'

In [ ]:
#you can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],
                    [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original Tensor is not changed

In [ ]:

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
import tensorflow as tf


In [ ]:
#Substraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#we can use tensorflow built-in function as well
tf.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix Multiplication
In machine learning matrix multiplication is one of the most common tensors operations

In [ ]:
#Matrix multiplication in tensorflow
import tensorflow as tf

In [ ]:
tensor=tf.constant([[10,7],
                    [4,3]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128,  91],
       [ 52,  37]], dtype=int32)>

In [ ]:
# create a tensor with different shape
Mat_A=tf.constant([[1,2,5],
                   [7,2,1],
                   [3,3,3]])
Mat_b=tf.constant([[3,5],
                   [6,7],
                   [1,8]])
Mat_A,Mat_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.matmul(Mat_A,Mat_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator "@"
Mat_A @ Mat_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#we can reshape the matrix easily as follows:

In [ ]:
tf.reshape(Mat_A,shape=(3,3))
Mat_A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
# Try multiplication using transpose 
tf.matmul(tf.transpose(Mat_A),Mat_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]], dtype=int32)>

**The dot product**
Matrix multiplcation is also referred to as the dot product.
you can perform matrix multliplication using
* `tf.matmul()`
* `tf.tensordot()`
* @

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
X=tf.constant([[1,2],
               [3,4],
               [5,6]])
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perform matrix multiplication between X and Y (transpose)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# perform matrix multiplication between X and Y (reshape)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y,"\n") # "\n" is  for new line
print("Y reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)),"\n")
print("Y transposed")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


 Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will tranpose (rather than reshape) of the tensors to get satisfy the matrix multliplication rule.

### Changing the data type of a tensor

In [ ]:
# to check the version of tensorflow
tf.__version__

'2.4.1'

In [ ]:
# Create a new tensor with new datatype (float 32)-
import tensorflow as tf
B=tf.constant([1.5,2.7,3.8])
B.dtype

tf.float32

In [ ]:
C=tf.constant([1,8,5])
C.dtype

tf.int32

In [ ]:
# Change from float 32 to float 16 (reduce precision)
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.5, 2.7, 3.8], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int 32 to float 32
E=tf.cast(C,dtype=tf.int32)
E,E.dtype

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 8, 5], dtype=int32)>,
 tf.int32)

In [ ]:
#change from float 32 to float 16 again
F=tf.cast(E,dtype=tf.float16)
F,F.dtype

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 8., 5.], dtype=float16)>,
 tf.float16)

### Aggregating tensors
Aggregating tensors  = condesing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50)) # random number generation starting from 0 to 100 and only 50 wota numbers
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 80, 61, 17, 34, 79, 59, 69, 78, 14, 50, 31, 91, 66, 59, 56, 64,
       40,  0, 39, 98, 26, 48, 49, 36, 14, 81, 86,  0, 86, 40, 11, 87, 44,
       18, 44, 61, 97, 43, 58, 80, 58, 96, 65, 82, 73, 51, 33, 76, 47])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2769>

In [ ]:
# Let's try to find variance and standard deviation of tensor `E`
V=tf.reduce_variance(E) # won't work...

AttributeError: ignored

In [ ]:
# To find variance of our tensor, we need to access to tensorflow_probability
import tensorflow_probability as tfp
V=tfp.stats.variance(E)
V

<tf.Tensor: shape=(), dtype=int64, numpy=686>

In [ ]:
# Find the standard deviation
tf.reduce_std(E)

AttributeError: ignored

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)) # to perform sd, the data type of tensor must be float 32 type...

<tf.Tensor: shape=(), dtype=float32, numpy=26.20755>

In [ ]:
# Find the variance of our E tensor using math function
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=686.83563>

### Find the positional maximum and minimum


In [ ]:
 # create a new tensor for finding positional minimum and maximum

 F=tf.random.uniform(shape=[50]) # each time i run this code, it will give me random 50 tensors.so to make each time the same tensor.i can use seed.
 F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2516998 , 0.9432062 , 0.01650476, 0.759115  , 0.9228071 ,
       0.57696545, 0.20745087, 0.33838582, 0.59246635, 0.813874  ,
       0.63977313, 0.41405106, 0.87057996, 0.46453464, 0.21241212,
       0.62557113, 0.62481534, 0.53842366, 0.76679444, 0.901351  ,
       0.10553956, 0.9258158 , 0.9957814 , 0.02517951, 0.8763112 ,
       0.01629639, 0.41777682, 0.33349085, 0.32761598, 0.3976878 ,
       0.69472957, 0.32698786, 0.7813107 , 0.8325342 , 0.78116965,
       0.43672287, 0.43912613, 0.93828106, 0.610718  , 0.93006635,
       0.0066365 , 0.4045235 , 0.41968405, 0.7955533 , 0.38195062,
       0.66066206, 0.77940905, 0.28091836, 0.01046789, 0.59208393],
      dtype=float32)>

In [ ]:
# each time i run the code,  i will get the same tensors
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for the equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#find the positional minimum
tf.argmin(F) # it gives us the position of index

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# to find the value at index 16 just above
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Let's check for equality
F[tf.argmin(F)]== tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### squeezing a tensor ( removing all the single dimensions)

In [ ]:
# create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G) # squeeze removes the dimensions of 1 from the tensors....

In [ ]:
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding

In [ ]:
# Create a list of indices
some_list=[0,1,2,3] #could be red,green,blue, purple

#One hot encoding our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

The result above shows that the element of list is encoded in logic format. 1st element is 1,0,0,0 and 2nd element is 0,1,0,0 and so on...

In [ ]:
# specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="Yes",off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

### squaring, log and square root

In [ ]:
# create  a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#square_root ( will create an error method requires non- int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
#square_root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tensors and Numpy
Tensorflow interacts beautifully with NumPy arrays.

In [ ]:
# Create tensor directly from NumPy
import numpy as np
J=tf.constant(np.array([3.,7.,100]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([  3.,   7., 100.])>

In [ ]:
#convery our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([  3.,   7., 100.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([  3.,   7., 100.]), numpy.ndarray)

In [ ]:
#the default type are slightly different
numpy_j=tf.constant(np.array([1.,3.,5,]))
tensor_j=tf.constant([3.,7.,10,])

#check the data types of both
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)